version: "3.7"

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.network=dian_network"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - default
      - dian_network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  dian_network:
   external: true